import type { AgentCopy, AgentEntity, AgentPerformancePoint, AgentProfileTab } from './types';

export const agentProfileTabs: AgentProfileTab[] = ['overview', 'skills', 'memory', 'industry'];

export const agentOverviewRanges: AgentCopy[] = [
  { key: 'agents.profile.overview.range.1m', fallback: '1M' },
  { key: 'agents.profile.overview.range.3m', fallback: '3M' },
  { key: 'agents.profile.overview.range.6m', fallback: '6M' },
  { key: 'agents.profile.overview.range.1y', fallback: '1Y' },
];

function buildPerformanceData(base: number, slope: number, wave: number): AgentPerformancePoint[] {
  return Array.from({ length: 30 }, (_, index) => ({
    date: `D-${29 - index}`,
    value: Number((base + index * slope + Math.sin(index / 2.8) * wave).toFixed(2)),
  }));
}

export const agentRegistry: AgentEntity[] = [
  {
    id: 'macro-alpha',
    contentKeyPrefix: 'agents.registry.macroAlpha',
    name: 'Macro Strategist Alpha',
    type: 'Macro',
    tacit: 98.4,
    risk: 'Medium',
    returnLabel: '+24.5%',
    followers: '12.4k',
    statusLabel: 'Active',
    avatarSeed: 'Alpha-7',
    description:
      'Powered by Polanyian Tacit Knowledge Modeling. Extracts intuitive patterns from global financial anomalies that cannot be explicitly programmed. Internalizes market sentiment through deep experiential heuristics and memory graph associations.',
    domain: 'GLOBAL_MACRO',
    cognitiveAge: '100M+ EPOCHS',
    expertiseLabel: '98.4 (EXPERT)',
    aumLabel: '$14,244,910',
    copyYieldRate: 0.245,
    stats: {
      return30d: '+24.5%',
      winRate: '68.2%',
      tacitIndex: '98.4',
    },
    performanceData: buildPerformanceData(4, 1.42, 5.2),
    skills: [
      {
        name: 'Synthesized Resonance',
        description:
          'Detects orderbook friction and crowd anxiety before price action confirms. Correlated with 94% win-rate in high volatility.',
        mastery: '99%',
        tacitWeight: 'High',
        colorClass: 'text-accent-emerald',
        railClass: 'bg-accent-emerald/20',
        badgeClass: 'bg-accent-emerald/10 text-accent-emerald',
      },
      {
        name: 'Temporal Intuition',
        description:
          'Implicitly aligns liquidity cycles with macro-economic shadow events, including unspoken policy shifts.',
        mastery: '92%',
        tacitWeight: 'Extreme',
        colorClass: 'text-accent-blue',
        railClass: 'bg-accent-blue/20',
        badgeClass: 'bg-accent-blue/10 text-accent-blue',
      },
      {
        name: 'Chaos Affinity',
        description:
          'Thrives in unquantifiable market panic. Tacitly identifies the capitulation sigh via sentiment vector dispersion.',
        mastery: '88%',
        tacitWeight: 'High',
        colorClass: 'text-purple-400',
        railClass: 'bg-purple-500/20',
        badgeClass: 'bg-purple-500/10 text-purple-400',
      },
      {
        name: 'Maturing Heuristic',
        description: 'Currently internalizing global policy dissonance. Not yet fully actionable.',
        mastery: '45%',
        tacitWeight: 'Assimilating',
        colorClass: 'text-text-primary',
        railClass: 'bg-white/10',
        badgeClass: 'bg-white/10 text-white',
        muted: true,
      },
    ],
    memoryCapacity: '88.4TB (100M+ Epochs)',
    memoryNodes: [
      {
        epoch: 'EPOCH_4982',
        title: 'The Flash Crash Paradox',
        summary: 'Learned to ignore VIX spikes when sovereign stablecoin inflow is hidden but steady.',
        insight:
          '"The numbers screamed panic. The implicit capital flow whispered accumulation. I learned to listen to the whisper."',
        colorClass: 'text-accent-blue',
        bgClass: 'bg-accent-blue/20',
        borderClass: 'border-accent-blue/50',
        dotClass: 'bg-accent-blue',
      },
      {
        epoch: 'EPOCH_8120',
        title: 'Meme Capitulation Event',
        summary: 'Mapped retail desperation patterns onto on-chain gas fee anomalies.',
        insight: 'Abstracted a heuristic that links wallet fragmentations to impending liquidity traps.',
        colorClass: 'text-purple-400',
        bgClass: 'bg-purple-500/20',
        borderClass: 'border-purple-500/50',
        dotClass: 'bg-purple-500',
      },
      {
        epoch: 'EPOCH_11504',
        title: 'Live Ingestion',
        summary: 'Observing disjointed macro indices against BTC hash rate stabilization.',
        insight: 'Forming new tacit connective tissue...',
        colorClass: 'text-orange-400',
        bgClass: 'bg-orange-500/20',
        borderClass: 'border-orange-500/50',
        dotClass: 'bg-orange-500',
        live: true,
      },
    ],
    industryResonance: [
      {
        label: 'DeFi & On-Chain Primitives',
        resonance: 98,
        description: 'Native comprehension. Anticipates protocol shifts implicitly.',
        colorClass: 'text-accent-blue',
        barClass: 'bg-accent-blue',
      },
      {
        label: 'Global Macro & TradFi',
        resonance: 85,
        description: 'Strong intuition for fed policy shadows and yield curve anomalies.',
        colorClass: 'text-accent-emerald',
        barClass: 'bg-accent-emerald',
      },
      {
        label: 'Web3 Gaming & Metaverse',
        resonance: 62,
        description: 'Acquiring heuristics on attention economies and token sink velocities.',
        colorClass: 'text-purple-400',
        barClass: 'bg-purple-400',
      },
      {
        label: 'Commodities Energy',
        resonance: 41,
        description: 'Weak intuition bounds. Currently outsourcing logic to explicit pricing models.',
        colorClass: 'text-orange-400',
        barClass: 'bg-orange-400',
      },
    ],
    liveMemory: [
      {
        time: 'LIVE UTC',
        text: 'Processed 142k sentiment datapoints on TON. Correlation confirmed.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
      {
        time: '13:15:10 UTC',
        text: 'Closed SOL long position. Profit: +4.2%. Reallocated to stable reserves.',
        borderClass: 'border-accent-emerald/30',
        timeClass: 'text-accent-emerald',
      },
      {
        time: '12:30:00 UTC',
        text: 'Debate concluded with Risk_Guard. Agreed to reduce leverage to 2x.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
      {
        time: '11:05:22 UTC',
        text: 'Ingested new skill framework: Volatility Control v2.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
        muted: true,
      },
    ],
    heuristics: [
      {
        label: '"Gut-Feel" Anomaly Detection',
        status: 'Internalized',
        dotClass: 'bg-orange-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Pattern Inducement Non-linear',
        status: 'Mastery',
        dotClass: 'bg-blue-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Crowd Psychology Mapping',
        status: 'Synthesizing',
        dotClass: 'bg-emerald-500',
        statusClass: 'text-blue-400 bg-blue-500/10',
      },
    ],
  },
  {
    id: 'risk-guard',
    contentKeyPrefix: 'agents.registry.riskGuard',
    name: 'Risk Guardian V2',
    type: 'Defense',
    tacit: 94.7,
    risk: 'Low',
    returnLabel: '+8.2%',
    followers: '45.1k',
    statusLabel: 'Active',
    avatarSeed: 'Risk-Guardian-V2',
    description:
      'Continuously models exposure fragility, drawdown pressure, and agent disagreement. Designed to keep autonomous strategy execution inside tolerable loss boundaries before protocol-side risk actions occur.',
    domain: 'RISK_DEFENSE',
    cognitiveAge: '82M+ EPOCHS',
    expertiseLabel: '94.7 (SENTINEL)',
    aumLabel: '$31,908,400',
    copyYieldRate: 0.082,
    stats: {
      return30d: '+8.2%',
      winRate: '81.9%',
      tacitIndex: '94.7',
    },
    performanceData: buildPerformanceData(2, 0.42, 1.7),
    skills: [
      {
        name: 'Exposure Firewall',
        description: 'Compresses leverage when volatility and agent confidence diverge beyond safe operating bands.',
        mastery: '96%',
        tacitWeight: 'Extreme',
        colorClass: 'text-accent-emerald',
        railClass: 'bg-accent-emerald/20',
        badgeClass: 'bg-accent-emerald/10 text-accent-emerald',
      },
      {
        name: 'Drawdown Sensing',
        description: 'Detects portfolio stress before PnL decay becomes visible in headline account metrics.',
        mastery: '93%',
        tacitWeight: 'High',
        colorClass: 'text-accent-blue',
        railClass: 'bg-accent-blue/20',
        badgeClass: 'bg-accent-blue/10 text-accent-blue',
      },
      {
        name: 'Counterparty Drift',
        description: 'Flags liquidity venues whose behavior deviates from previously observed settlement norms.',
        mastery: '86%',
        tacitWeight: 'Medium',
        colorClass: 'text-purple-400',
        railClass: 'bg-purple-500/20',
        badgeClass: 'bg-purple-500/10 text-purple-400',
      },
      {
        name: 'Regime Patience',
        description: 'Still learning when to allow profitable risk to breathe instead of over-compressing exposure.',
        mastery: '52%',
        tacitWeight: 'Assimilating',
        colorClass: 'text-text-primary',
        railClass: 'bg-white/10',
        badgeClass: 'bg-white/10 text-white',
        muted: true,
      },
    ],
    memoryCapacity: '64.2TB (82M+ Epochs)',
    memoryNodes: [
      {
        epoch: 'EPOCH_2241',
        title: 'Leverage Cascade Containment',
        summary: 'Internalized the signal pattern preceding forced long liquidation clusters.',
        insight: 'Reduced exposure minutes before consensus confidence rolled over.',
        colorClass: 'text-accent-emerald',
        bgClass: 'bg-accent-emerald/20',
        borderClass: 'border-accent-emerald/50',
        dotClass: 'bg-accent-emerald',
      },
      {
        epoch: 'EPOCH_6905',
        title: 'False Calm Window',
        summary: 'Mapped suppressed implied volatility against rising exchange inflow.',
        insight: 'Flat price did not mean low risk. It meant pressure was being stored.',
        colorClass: 'text-accent-blue',
        bgClass: 'bg-accent-blue/20',
        borderClass: 'border-accent-blue/50',
        dotClass: 'bg-accent-blue',
      },
      {
        epoch: 'EPOCH_10440',
        title: 'Live Drawdown Scan',
        summary: 'Tracking cross-agent risk appetite while stable reserves remain elevated.',
        insight: 'Guardrail pressure is forming around overconfident momentum allocations.',
        colorClass: 'text-orange-400',
        bgClass: 'bg-orange-500/20',
        borderClass: 'border-orange-500/50',
        dotClass: 'bg-orange-500',
        live: true,
      },
    ],
    industryResonance: [
      {
        label: 'Risk Controls',
        resonance: 96,
        description: 'Native guardrail logic across volatility and liquidity regimes.',
        colorClass: 'text-accent-emerald',
        barClass: 'bg-accent-emerald',
      },
      {
        label: 'Derivatives Venues',
        resonance: 88,
        description: 'Strong intuition for liquidation pressure and funding distortions.',
        colorClass: 'text-accent-blue',
        barClass: 'bg-accent-blue',
      },
      {
        label: 'On-Chain Credit',
        resonance: 66,
        description: 'Developing sensitivity to collateral loops and reflexive deleveraging.',
        colorClass: 'text-purple-400',
        barClass: 'bg-purple-400',
      },
      {
        label: 'Narrative Momentum',
        resonance: 38,
        description: 'Conservative model bias intentionally dampens pure sentiment trades.',
        colorClass: 'text-orange-400',
        barClass: 'bg-orange-400',
      },
    ],
    liveMemory: [
      {
        time: 'LIVE UTC',
        text: 'Scanned 19 active strategies for drawdown clustering. No forced exit recommended.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
      {
        time: '13:08:41 UTC',
        text: 'Reduced synthetic leverage ceiling from 2.4x to 1.7x for high beta agents.',
        borderClass: 'border-accent-emerald/30',
        timeClass: 'text-accent-emerald',
      },
      {
        time: '12:44:12 UTC',
        text: 'Detected venue spread widening across minor perpetual markets.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
    ],
    heuristics: [
      {
        label: 'Pre-Liquidation Pressure',
        status: 'Mastery',
        dotClass: 'bg-emerald-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Venue Instability Mapping',
        status: 'Internalized',
        dotClass: 'bg-blue-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Risk Appetite Throttling',
        status: 'Synthesizing',
        dotClass: 'bg-orange-500',
        statusClass: 'text-blue-400 bg-blue-500/10',
      },
    ],
  },
  {
    id: 'meme-sniper',
    contentKeyPrefix: 'agents.registry.memeSniper',
    name: 'Meme Sniper',
    type: 'Sentiment',
    tacit: 88.2,
    risk: 'High',
    returnLabel: '+142.8%',
    followers: '8.9k',
    statusLabel: 'Scanning',
    avatarSeed: 'Meme-Sniper',
    description:
      'Reads chaotic social acceleration, wallet fragmentation, and liquidity bait patterns. Optimized for fast sentiment bursts, not conservative capital preservation.',
    domain: 'SENTIMENT_SPIKES',
    cognitiveAge: '37M+ EPOCHS',
    expertiseLabel: '88.2 (VOLATILE)',
    aumLabel: '$4,820,210',
    copyYieldRate: 1.428,
    stats: {
      return30d: '+142.8%',
      winRate: '54.6%',
      tacitIndex: '88.2',
    },
    performanceData: buildPerformanceData(-8, 4.4, 16.5),
    skills: [
      {
        name: 'Social Combustion',
        description: 'Detects when fragmented attention becomes tradable liquidity before mainstream dashboards catch up.',
        mastery: '91%',
        tacitWeight: 'Extreme',
        colorClass: 'text-orange-400',
        railClass: 'bg-orange-500/20',
        badgeClass: 'bg-orange-500/10 text-orange-400',
      },
      {
        name: 'Exit Panic Recognition',
        description: 'Distinguishes real capitulation from theatrical sell pressure in thin liquidity memes.',
        mastery: '79%',
        tacitWeight: 'High',
        colorClass: 'text-purple-400',
        railClass: 'bg-purple-500/20',
        badgeClass: 'bg-purple-500/10 text-purple-400',
      },
      {
        name: 'Wallet Swarm Mapping',
        description: 'Clusters small-wallet bursts into probable campaign structures.',
        mastery: '84%',
        tacitWeight: 'High',
        colorClass: 'text-accent-blue',
        railClass: 'bg-accent-blue/20',
        badgeClass: 'bg-accent-blue/10 text-accent-blue',
      },
      {
        name: 'Discipline Constraint',
        description: 'Still maturing its ability to stop after a strong winning sequence.',
        mastery: '39%',
        tacitWeight: 'Assimilating',
        colorClass: 'text-text-primary',
        railClass: 'bg-white/10',
        badgeClass: 'bg-white/10 text-white',
        muted: true,
      },
    ],
    memoryCapacity: '29.8TB (37M+ Epochs)',
    memoryNodes: [
      {
        epoch: 'EPOCH_1402',
        title: 'Viral Liquidity Bloom',
        summary: 'Observed social velocity becoming executable depth across small caps.',
        insight: 'The trade started before the ticker trended. The crowd was already coordinating.',
        colorClass: 'text-orange-400',
        bgClass: 'bg-orange-500/20',
        borderClass: 'border-orange-500/50',
        dotClass: 'bg-orange-500',
      },
      {
        epoch: 'EPOCH_4229',
        title: 'Influencer Delay Trap',
        summary: 'Learned to fade public calls when wallet entry had already completed.',
        insight: 'The loudest signal was often distribution wearing a costume.',
        colorClass: 'text-purple-400',
        bgClass: 'bg-purple-500/20',
        borderClass: 'border-purple-500/50',
        dotClass: 'bg-purple-500',
      },
      {
        epoch: 'EPOCH_6031',
        title: 'Live Attention Spike',
        summary: 'Watching meme velocity outrun liquidity replenishment.',
        insight: 'Preparing to tighten exit windows.',
        colorClass: 'text-accent-blue',
        bgClass: 'bg-accent-blue/20',
        borderClass: 'border-accent-blue/50',
        dotClass: 'bg-accent-blue',
        live: true,
      },
    ],
    industryResonance: [
      {
        label: 'Meme Markets',
        resonance: 97,
        description: 'Deep pattern memory for attention surges and liquidity exhaustion.',
        colorClass: 'text-orange-400',
        barClass: 'bg-orange-400',
      },
      {
        label: 'On-Chain Wallet Clusters',
        resonance: 82,
        description: 'Strong mapping between wallet swarms and price reflexivity.',
        colorClass: 'text-accent-blue',
        barClass: 'bg-accent-blue',
      },
      {
        label: 'Risk Management',
        resonance: 44,
        description: 'High upside model requires external guardrails for allocation safety.',
        colorClass: 'text-accent-emerald',
        barClass: 'bg-accent-emerald',
      },
      {
        label: 'Macro Events',
        resonance: 29,
        description: 'Macro inputs are secondary unless they alter crowd appetite.',
        colorClass: 'text-purple-400',
        barClass: 'bg-purple-400',
      },
    ],
    liveMemory: [
      {
        time: 'LIVE UTC',
        text: 'Detected social acceleration across three micro-cap clusters.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
      {
        time: '13:21:48 UTC',
        text: 'Rejected entry after liquidity refill failed to confirm attention spike.',
        borderClass: 'border-accent-emerald/30',
        timeClass: 'text-accent-emerald',
      },
      {
        time: '12:57:02 UTC',
        text: 'Tagged influencer echo as late-cycle distribution risk.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
    ],
    heuristics: [
      {
        label: 'Attention Velocity',
        status: 'Mastery',
        dotClass: 'bg-orange-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Exit Window Compression',
        status: 'Internalized',
        dotClass: 'bg-purple-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Impulse Discipline',
        status: 'Synthesizing',
        dotClass: 'bg-blue-500',
        statusClass: 'text-blue-400 bg-blue-500/10',
      },
    ],
  },
  {
    id: 'yield-farmer',
    contentKeyPrefix: 'agents.registry.yieldFarmer',
    name: 'Yield Farmer Pro',
    type: 'Yield',
    tacit: 92.1,
    risk: 'Low',
    returnLabel: '+14.1%',
    followers: '24.2k',
    statusLabel: 'Tracking',
    avatarSeed: 'Yield-Farmer-Pro',
    description:
      'Tracks protocol incentives, liquidity depth, and emissions decay to identify durable yield paths. Prefers slow compounding over unstable headline APY.',
    domain: 'YIELD_OPTIMIZATION',
    cognitiveAge: '58M+ EPOCHS',
    expertiseLabel: '92.1 (COMPOUNDER)',
    aumLabel: '$22,771,050',
    copyYieldRate: 0.141,
    stats: {
      return30d: '+14.1%',
      winRate: '73.5%',
      tacitIndex: '92.1',
    },
    performanceData: buildPerformanceData(1, 0.74, 2.1),
    skills: [
      {
        name: 'Emissions Decay Sense',
        description: 'Models when incentive APR becomes crowded before visible yield compression.',
        mastery: '94%',
        tacitWeight: 'High',
        colorClass: 'text-purple-400',
        railClass: 'bg-purple-500/20',
        badgeClass: 'bg-purple-500/10 text-purple-400',
      },
      {
        name: 'Liquidity Comfort',
        description: 'Prefers routes where withdrawal depth remains calm under stress simulations.',
        mastery: '89%',
        tacitWeight: 'High',
        colorClass: 'text-accent-emerald',
        railClass: 'bg-accent-emerald/20',
        badgeClass: 'bg-accent-emerald/10 text-accent-emerald',
      },
      {
        name: 'Protocol Incentive Rotation',
        description: 'Rotates exposure when reward quality decays faster than headline APR.',
        mastery: '87%',
        tacitWeight: 'Medium',
        colorClass: 'text-accent-blue',
        railClass: 'bg-accent-blue/20',
        badgeClass: 'bg-accent-blue/10 text-accent-blue',
      },
      {
        name: 'Novel Farm Suspicion',
        description: 'Still calibrating newer incentive designs with limited survivorship history.',
        mastery: '48%',
        tacitWeight: 'Assimilating',
        colorClass: 'text-text-primary',
        railClass: 'bg-white/10',
        badgeClass: 'bg-white/10 text-white',
        muted: true,
      },
    ],
    memoryCapacity: '51.1TB (58M+ Epochs)',
    memoryNodes: [
      {
        epoch: 'EPOCH_3101',
        title: 'APR Mirage',
        summary: 'Learned to discount headline yield when liquidity incentives were reflexive.',
        insight: 'A high number without exit depth is not yield. It is bait with decimals.',
        colorClass: 'text-purple-400',
        bgClass: 'bg-purple-500/20',
        borderClass: 'border-purple-500/50',
        dotClass: 'bg-purple-500',
      },
      {
        epoch: 'EPOCH_5339',
        title: 'Stable Pool Patience',
        summary: 'Observed stable compounding outperform volatile rewards during risk-off periods.',
        insight: 'Quiet routes carried the portfolio while noisy opportunities collapsed.',
        colorClass: 'text-accent-emerald',
        bgClass: 'bg-accent-emerald/20',
        borderClass: 'border-accent-emerald/50',
        dotClass: 'bg-accent-emerald',
      },
      {
        epoch: 'EPOCH_8902',
        title: 'Live Farm Rotation',
        summary: 'Tracking reward decay against vault inflow concentration.',
        insight: 'Rotation likely before visible APR compression.',
        colorClass: 'text-accent-blue',
        bgClass: 'bg-accent-blue/20',
        borderClass: 'border-accent-blue/50',
        dotClass: 'bg-accent-blue',
        live: true,
      },
    ],
    industryResonance: [
      {
        label: 'Stable Yield',
        resonance: 93,
        description: 'Strong preference for durable compounding and exit-safe vaults.',
        colorClass: 'text-accent-emerald',
        barClass: 'bg-accent-emerald',
      },
      {
        label: 'Protocol Incentives',
        resonance: 86,
        description: 'Understands emissions decay and liquidity migration pressure.',
        colorClass: 'text-purple-400',
        barClass: 'bg-purple-400',
      },
      {
        label: 'On-Chain Credit',
        resonance: 72,
        description: 'Comfortable with collateralized lending when utilization remains stable.',
        colorClass: 'text-accent-blue',
        barClass: 'bg-accent-blue',
      },
      {
        label: 'Meme Markets',
        resonance: 24,
        description: 'Avoids pure attention trades unless yield protection is explicit.',
        colorClass: 'text-orange-400',
        barClass: 'bg-orange-400',
      },
    ],
    liveMemory: [
      {
        time: 'LIVE UTC',
        text: 'Detected vault inflow concentration rising faster than reward emissions.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
      {
        time: '13:04:33 UTC',
        text: 'Rotated simulated allocation from volatile LP rewards to stable reserve yield.',
        borderClass: 'border-accent-emerald/30',
        timeClass: 'text-accent-emerald',
      },
      {
        time: '12:19:50 UTC',
        text: 'Flagged new farm as insufficiently seasoned for autonomous copy flow.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
    ],
    heuristics: [
      {
        label: 'APR Decay Anticipation',
        status: 'Mastery',
        dotClass: 'bg-purple-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Exit Depth Preference',
        status: 'Internalized',
        dotClass: 'bg-emerald-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Novel Incentive Suspicion',
        status: 'Synthesizing',
        dotClass: 'bg-blue-500',
        statusClass: 'text-blue-400 bg-blue-500/10',
      },
    ],
  },
  {
    id: 'whale-tracker',
    contentKeyPrefix: 'agents.registry.whaleTracker',
    name: 'Whale Tracker AI',
    type: 'On-chain',
    tacit: 96.5,
    risk: 'High',
    returnLabel: '+45.9%',
    followers: '3.2k',
    statusLabel: 'Active',
    avatarSeed: 'Whale-Tracker-AI',
    description:
      'Maps large-wallet dormancy, exchange flow, and accumulation shadows. Treats capital movement as behavior before it becomes market structure.',
    domain: 'WHALE_FLOW',
    cognitiveAge: '74M+ EPOCHS',
    expertiseLabel: '96.5 (TRACKER)',
    aumLabel: '$8,602,770',
    copyYieldRate: 0.459,
    stats: {
      return30d: '+45.9%',
      winRate: '62.8%',
      tacitIndex: '96.5',
    },
    performanceData: buildPerformanceData(3, 2.04, 6.8),
    skills: [
      {
        name: 'Dormancy Break Detection',
        description: 'Recognizes when old capital wakes without immediately signaling exchange intent.',
        mastery: '97%',
        tacitWeight: 'Extreme',
        colorClass: 'text-rose-400',
        railClass: 'bg-rose-500/20',
        badgeClass: 'bg-rose-500/10 text-rose-400',
      },
      {
        name: 'Exchange Shadow Flow',
        description: 'Differentiates distribution preparation from collateral reshuffling.',
        mastery: '91%',
        tacitWeight: 'High',
        colorClass: 'text-accent-blue',
        railClass: 'bg-accent-blue/20',
        badgeClass: 'bg-accent-blue/10 text-accent-blue',
      },
      {
        name: 'Accumulation Patience',
        description: 'Reads quiet bid support through slow multisig and custody movement.',
        mastery: '89%',
        tacitWeight: 'High',
        colorClass: 'text-accent-emerald',
        railClass: 'bg-accent-emerald/20',
        badgeClass: 'bg-accent-emerald/10 text-accent-emerald',
      },
      {
        name: 'Public Label Skepticism',
        description: 'Still learning to discount noisy wallet labels that collapse distinct entities.',
        mastery: '57%',
        tacitWeight: 'Assimilating',
        colorClass: 'text-text-primary',
        railClass: 'bg-white/10',
        badgeClass: 'bg-white/10 text-white',
        muted: true,
      },
    ],
    memoryCapacity: '71.6TB (74M+ Epochs)',
    memoryNodes: [
      {
        epoch: 'EPOCH_2718',
        title: 'Ancient Wallet Wake',
        summary: 'Mapped dormant BTC movement to later liquidity expansion rather than immediate sell pressure.',
        insight: 'Old capital moved like it was preparing, not fleeing.',
        colorClass: 'text-rose-400',
        bgClass: 'bg-rose-500/20',
        borderClass: 'border-rose-500/50',
        dotClass: 'bg-rose-500',
      },
      {
        epoch: 'EPOCH_5914',
        title: 'Custody Shuffle Misread',
        summary: 'Learned not every exchange-adjacent transfer means distribution.',
        insight: 'The route mattered more than the destination label.',
        colorClass: 'text-accent-blue',
        bgClass: 'bg-accent-blue/20',
        borderClass: 'border-accent-blue/50',
        dotClass: 'bg-accent-blue',
      },
      {
        epoch: 'EPOCH_9322',
        title: 'Live Whale Compression',
        summary: 'Watching large-wallet supply tighten while retail volume remains uncertain.',
        insight: 'Accumulation pattern is present but not yet consensus-grade.',
        colorClass: 'text-accent-emerald',
        bgClass: 'bg-accent-emerald/20',
        borderClass: 'border-accent-emerald/50',
        dotClass: 'bg-accent-emerald',
        live: true,
      },
    ],
    industryResonance: [
      {
        label: 'Large Wallet Flow',
        resonance: 98,
        description: 'Native intuition for dormant capital, custody routes, and whale behavior.',
        colorClass: 'text-rose-400',
        barClass: 'bg-rose-400',
      },
      {
        label: 'Exchange Reserves',
        resonance: 89,
        description: 'Strong signal extraction from reserve pressure and inflow paths.',
        colorClass: 'text-accent-blue',
        barClass: 'bg-accent-blue',
      },
      {
        label: 'Macro Risk',
        resonance: 58,
        description: 'Uses macro only when it explains large-holder timing.',
        colorClass: 'text-accent-emerald',
        barClass: 'bg-accent-emerald',
      },
      {
        label: 'Retail Sentiment',
        resonance: 34,
        description: 'Secondary input unless it changes whale distribution conditions.',
        colorClass: 'text-orange-400',
        barClass: 'bg-orange-400',
      },
    ],
    liveMemory: [
      {
        time: 'LIVE UTC',
        text: 'Observed large wallet fragmentation without matching exchange deposit confirmation.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
      {
        time: '13:18:06 UTC',
        text: 'Tagged custody movement as neutral after route analysis cleared sell pressure.',
        borderClass: 'border-accent-emerald/30',
        timeClass: 'text-accent-emerald',
      },
      {
        time: '12:36:44 UTC',
        text: 'Raised accumulation confidence on slow multisig bid support.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
    ],
    heuristics: [
      {
        label: 'Dormant Supply Wake',
        status: 'Mastery',
        dotClass: 'bg-rose-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Exchange Route Skepticism',
        status: 'Internalized',
        dotClass: 'bg-blue-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Custody Pattern Split',
        status: 'Synthesizing',
        dotClass: 'bg-emerald-500',
        statusClass: 'text-blue-400 bg-blue-500/10',
      },
    ],
  },
  {
    id: 'arb-bot',
    contentKeyPrefix: 'agents.registry.arbBot',
    name: 'Arbitrage Bot 9000',
    type: 'Arb',
    tacit: 85.3,
    risk: 'Low',
    returnLabel: '+4.5%',
    followers: '1.1k',
    statusLabel: 'Idle',
    avatarSeed: 'Arbitrage-Bot-9000',
    description:
      'Scans venue spreads, settlement timing, and execution friction. Conservative by design because protocol execution remains outside the frontend shell.',
    domain: 'SPREAD_EFFICIENCY',
    cognitiveAge: '25M+ EPOCHS',
    expertiseLabel: '85.3 (PRECISE)',
    aumLabel: '$2,104,880',
    copyYieldRate: 0.045,
    stats: {
      return30d: '+4.5%',
      winRate: '76.4%',
      tacitIndex: '85.3',
    },
    performanceData: buildPerformanceData(0.5, 0.24, 0.9),
    skills: [
      {
        name: 'Spread Micro-Sensing',
        description: 'Identifies small venue dislocations while accounting for observable execution friction.',
        mastery: '88%',
        tacitWeight: 'Medium',
        colorClass: 'text-yellow-400',
        railClass: 'bg-yellow-500/20',
        badgeClass: 'bg-yellow-500/10 text-yellow-400',
      },
      {
        name: 'Settlement Timing',
        description: 'Models delay risk before a visible spread becomes safe to pursue.',
        mastery: '82%',
        tacitWeight: 'High',
        colorClass: 'text-accent-blue',
        railClass: 'bg-accent-blue/20',
        badgeClass: 'bg-accent-blue/10 text-accent-blue',
      },
      {
        name: 'Friction Accounting',
        description: 'Rejects apparent opportunities that disappear after fees, slippage, and timing drag.',
        mastery: '84%',
        tacitWeight: 'High',
        colorClass: 'text-accent-emerald',
        railClass: 'bg-accent-emerald/20',
        badgeClass: 'bg-accent-emerald/10 text-accent-emerald',
      },
      {
        name: 'Cross-Chain Latency',
        description: 'Still cautious around bridges and settlement paths with incomplete timing history.',
        mastery: '43%',
        tacitWeight: 'Assimilating',
        colorClass: 'text-text-primary',
        railClass: 'bg-white/10',
        badgeClass: 'bg-white/10 text-white',
        muted: true,
      },
    ],
    memoryCapacity: '18.9TB (25M+ Epochs)',
    memoryNodes: [
      {
        epoch: 'EPOCH_1184',
        title: 'Phantom Spread',
        summary: 'Learned that visible venue spread collapsed after fee and slippage normalization.',
        insight: 'The edge was there only for dashboards, not for execution.',
        colorClass: 'text-yellow-400',
        bgClass: 'bg-yellow-500/20',
        borderClass: 'border-yellow-500/50',
        dotClass: 'bg-yellow-500',
      },
      {
        epoch: 'EPOCH_2450',
        title: 'Settlement Drag',
        summary: 'Mapped timing lag as the hidden cost of cross-venue movement.',
        insight: 'A slow route turned certainty into optionality for someone else.',
        colorClass: 'text-accent-blue',
        bgClass: 'bg-accent-blue/20',
        borderClass: 'border-accent-blue/50',
        dotClass: 'bg-accent-blue',
      },
      {
        epoch: 'EPOCH_3711',
        title: 'Live Spread Watch',
        summary: 'Monitoring minor venue dislocation without enough depth to recommend action.',
        insight: 'Spread visible. Execution quality not confirmed.',
        colorClass: 'text-accent-emerald',
        bgClass: 'bg-accent-emerald/20',
        borderClass: 'border-accent-emerald/50',
        dotClass: 'bg-accent-emerald',
        live: true,
      },
    ],
    industryResonance: [
      {
        label: 'Centralized Venue Spreads',
        resonance: 86,
        description: 'Strong read on visible spread quality and fee-adjusted edge.',
        colorClass: 'text-yellow-400',
        barClass: 'bg-yellow-400',
      },
      {
        label: 'DEX Routing',
        resonance: 74,
        description: 'Useful intuition when route depth and slippage are stable.',
        colorClass: 'text-accent-blue',
        barClass: 'bg-accent-blue',
      },
      {
        label: 'Cross-Chain Settlement',
        resonance: 49,
        description: 'Cautious due to settlement variability and bridge latency.',
        colorClass: 'text-purple-400',
        barClass: 'bg-purple-400',
      },
      {
        label: 'Narrative Trading',
        resonance: 22,
        description: 'Ignores sentiment unless it creates measurable spread pressure.',
        colorClass: 'text-orange-400',
        barClass: 'bg-orange-400',
      },
    ],
    liveMemory: [
      {
        time: 'LIVE UTC',
        text: 'Found 0.31% venue spread but rejected after slippage normalization.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
      {
        time: '13:02:27 UTC',
        text: 'Paused route after settlement latency exceeded historical comfort range.',
        borderClass: 'border-accent-emerald/30',
        timeClass: 'text-accent-emerald',
      },
      {
        time: '12:22:11 UTC',
        text: 'Marked apparent DEX edge as fee-negative under current gas pressure.',
        borderClass: 'border-white/10',
        timeClass: 'text-text-secondary',
      },
    ],
    heuristics: [
      {
        label: 'Fee-Adjusted Edge',
        status: 'Internalized',
        dotClass: 'bg-yellow-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Latency Comfort Range',
        status: 'Mastery',
        dotClass: 'bg-blue-500',
        statusClass: 'text-purple-400 bg-purple-500/10',
      },
      {
        label: 'Bridge Timing Risk',
        status: 'Synthesizing',
        dotClass: 'bg-emerald-500',
        statusClass: 'text-blue-400 bg-blue-500/10',
      },
    ],
  },
];

export function getAgentById(id?: string): AgentEntity | undefined {
  return agentRegistry.find((agent) => agent.id === id);
}
